# Generated by Django 4.2.30 on 2026-07-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_contrat_statut_choices'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope_departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_users', to='employees.departement', verbose_name='Périmètre — Département'),
        ),
        migrations.AddField(
            model_name='user',
            name='scope_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_users', to='employees.direction', verbose_name='Périmètre — Direction'),
        ),
        migrations.AddField(
            model_name='user',
            name='scope_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_users', to='employees.service', verbose_name='Périmètre — Service'),
        ),
    ]
