# Generated by Django 4.2.30 on 2026-07-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_photo'),
        ('accounts', '0005_remove_old_scope_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope_types_documents',
            field=models.ManyToManyField(blank=True, related_name='scoped_users', to='employees.typedocument', verbose_name='Périmètre — Types de documents'),
        ),
    ]
