# Generated by Django 4.2.30 on 2026-08-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_pole_cellule'),
        ('accounts', '0006_user_scope_types_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope_cellules',
            field=models.ManyToManyField(blank=True, related_name='scoped_users', to='employees.cellule', verbose_name='Périmètre — Cellules'),
        ),
        migrations.AddField(
            model_name='user',
            name='scope_poles',
            field=models.ManyToManyField(blank=True, related_name='scoped_users', to='employees.pole', verbose_name='Périmètre — Pôles'),
        ),
    ]
