# Generated by Django 4.2.30 on 2026-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_scope_cellules_user_scope_poles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_loi1807_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentement Loi 18-07 accepté le'),
        ),
    ]
