# Generated by Django 4.2.30 on 2026-08-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_section_employee_section'),
        ('accounts', '0008_user_consent_loi1807_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope_sections',
            field=models.ManyToManyField(blank=True, related_name='scoped_users', to='employees.section', verbose_name='Périmètre — Sections'),
        ),
    ]
