# Generated by Django 4.2.30 on 2026-08-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_scope_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super-administrateur'), ('ADMIN', 'Administrateur'), ('CONSULTANT', 'Consultant (lecture seule)')], default='CONSULTANT', max_length=20, verbose_name='Rôle'),
        ),
    ]
