# Generated by Django 4.2.30 on 2026-09-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_seed_champs_systeme'),
        ('accounts', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope_champs_personnels',
            field=models.ManyToManyField(blank=True, related_name='scoped_users', to='employees.champpersonnalise', verbose_name='Périmètre — Champs personnels'),
        ),
    ]
