# Generated by Django 4.2.30 on 2026-09-14 08:34
"""
Supprime les vestiges d'un ancien modèle "Unité organisationnelle"
(précurseur de Direction/Departement/Service/Cellule/Section), absent du
code Django actuel mais toujours présent en base sous 3 formes :
- `unites_organisationnelles` (88 lignes) et sa table de jointure M2M
  `auth_users_scope_unites` (67 lignes, ancien `User.scope_unites`) —
  bloquait toute suppression d'un compte CONSULTANT ayant un périmètre
  configuré via l'ancien système (ForeignKeyViolation sur
  auth_users_scope_unites_user_id).
- `employees.unite_organisationnelle_id`, colonne orpheline (1 seul
  employé concerné, matricule 013151) sans équivalent dans le modèle
  Employee actuel (qui utilise direction/departement/service/cellule/
  section depuis longtemps).
Sauvegarde JSON complète des 3 avant application (voir conversation du
2026-09-14).
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_updated_at_user_updated_by'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE employees DROP COLUMN IF EXISTS unite_organisationnelle_id;",
                "DROP TABLE IF EXISTS auth_users_scope_unites;",
                "DROP TABLE IF EXISTS unites_organisationnelles;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
