# Generated by Django 5.2.17 on 2026-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_drop_orphan_unites_organisationnelles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='libelle_role',
            field=models.CharField(blank=True, help_text="Ex. 'Secrétaire', 'Superviseur' — remplace 'Gestionnaire' dans l'interface pour ce compte, sans changer ses permissions.", max_length=50, verbose_name="Libellé d'affichage"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super-administrateur'), ('ADMIN', 'Administrateur'), ('GESTIONNAIRE', 'Gestionnaire'), ('CONSULTANT', 'Consultant (lecture seule)')], default='CONSULTANT', max_length=20, verbose_name='Rôle'),
        ),
    ]
