# Generated by Django 5.2.17 on 2026-09-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_gestionnaire_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='charge_attestation',
            field=models.BooleanField(default=False, help_text="Réservé aux comptes Administrateur : reçoit et traite les demandes d'attestation de travail (/attestations). Un Super-administrateur y a toujours accès, quel que soit ce champ.", verbose_name='Chargé des attestations de travail'),
        ),
    ]
