# Generated by Django 5.2.17 on 2026-10-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ATTESTATION_NOUVELLE', "Nouvelle demande d'attestation"), ('ATTESTATION_PRETE', 'Attestation prête'), ('ATTESTATION_REJETEE', 'Attestation rejetée'), ('COMPTE_VERROUILLE', 'Compte verrouillé'), ('EMPLOYE_TRANSFERE', 'Employé transféré'), ('EMPLOYE_ARCHIVE', 'Employé archivé'), ('IMPORT_TERMINE', 'Import terminé'), ('CONTRAT_ECHEANCE', "Contrat proche de l'échéance"), ('GENERIQUE', 'Générique')], default='GENERIQUE', max_length=40),
        ),
    ]
