# Generated by Django 5.2.17 on 2026-09-22 18:46

import attestations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0036_champ_personnalise_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe_nom', models.CharField(default='SOMIZ', max_length=100)),
                ('societe_soustitre', models.CharField(blank=True, max_length=255)),
                ('societe_capital', models.CharField(blank=True, max_length=255)),
                ('holding', models.CharField(blank=True, max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('telex', models.CharField(blank=True, max_length=50)),
                ('signataire_titre', models.CharField(blank=True, max_length=150)),
                ('signataire_nom', models.CharField(blank=True, max_length=150)),
                ('texte_intro', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=attestations.models.attestation_logo_upload_path)),
            ],
            options={
                'db_table': 'attestation_template_config',
            },
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(unique=True)),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'attestation_reference_counters',
            },
        ),
        migrations.CreateModel(
            name='DemandeAttestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('motif', models.CharField(max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('imprimee', 'Imprimée'), ('signee', 'Signée'), ('prete', 'Prête'), ('recuperee', 'Récupérée'), ('rejetee', 'Rejetée')], default='recue', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('scan_document', models.FileField(blank=True, null=True, upload_to=attestations.models.attestation_scan_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_attestation', to='employees.contrat')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_attestation_faites', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_attestation', to='employees.employee')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_attestation_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demandes_attestation',
                'ordering': ['-created_at'],
            },
        ),
    ]
