# Generated by Django 5.2.17 on 2026-09-22 20:14

from django.db import migrations, models

# Valeurs relevées sur le modèle papier SOMIZ en vigueur — appliquées aux
# champs restés vides de la configuration déjà créée (les nouveaux `default`
# du modèle ne s'appliquent qu'aux lignes créées ensuite).
VALEURS_MODELE = {
    'societe_soustitre': "SOCIÉTÉ DE MAINTENANCE INDUSTRIELLE D'ARZEW",
    'societe_capital': "SPA Au Capital Social de 3.700.000.000 DA",
    'holding': "Holding SONATRACH Services Parapétroliers Spa",
    'adresse': "BP 28 Route d'El Mohgoun 31200 Arzew",
    'ville': "Arzew",
    'telephone': "213 (0) 41.68.01.00",
    'fax': "213 (0) 41.68.01.63",
    'telex': "12048 DZ",
    'signataire_titre': "Chef de Département Administration du Personnel",
    'signataire_nom': "A.BOUSMAHA",
}


def remplir_config_existante(apps, schema_editor):
    Config = apps.get_model('attestations', 'AttestationTemplateConfig')
    for config in Config.objects.all():
        modifie = []
        for champ, valeur in VALEURS_MODELE.items():
            if not getattr(config, champ, ''):
                setattr(config, champ, valeur)
                modifie.append(champ)
        if modifie:
            config.save(update_fields=modifie)


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestationtemplateconfig',
            name='texte_intro',
        ),
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='adresse',
            field=models.CharField(blank=True, default="BP 28 Route d'El Mohgoun 31200 Arzew", max_length=255),
        ),
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='fax',
            field=models.CharField(blank=True, default='213 (0) 41.68.01.63', max_length=50),
        ),
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='holding',
            field=models.CharField(blank=True, default='Holding SONATRACH Services Parapétroliers Spa', max_length=255),
        ),
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='signataire_titre',
            field=models.CharField(blank=True, default='Chef de Département Administration du Personnel', max_length=150),
        ),
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='societe_capital',
            field=models.CharField(blank=True, default='SPA Au Capital Social de 3.700.000.000 DA', max_length=255),
        ),
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='societe_soustitre',
            field=models.CharField(blank=True, default="SOCIÉTÉ DE MAINTENANCE INDUSTRIELLE D'ARZEW", max_length=255),
        ),
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='telephone',
            field=models.CharField(blank=True, default='213 (0) 41.68.01.00', max_length=50),
        ),
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='telex',
            field=models.CharField(blank=True, default='12048 DZ', max_length=50),
        ),
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='ville',
            field=models.CharField(blank=True, default='Arzew', max_length=100),
        ),
        migrations.RunPython(remplir_config_existante, migrations.RunPython.noop),
    ]
