# Generated by Django 5.2.17 on 2026-09-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0002_config_defaults_modele_papier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationtemplateconfig',
            name='signataire_nom',
            field=models.CharField(blank=True, default='A.BOUSMAHA', max_length=150),
        ),
    ]
