# Generated by Django 5.2.17 on 2026-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0004_motif_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationtemplateconfig',
            name='signataire_interim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attestationtemplateconfig',
            name='signataire_interim_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
