# Generated by Django 5.2.17 on 2026-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0005_attestationtemplateconfig_signataire_interim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeattestation',
            name='date_document',
            field=models.DateField(blank=True, null=True),
        ),
    ]
