# Generated by Django 5.2.17 on 2026-09-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0007_drop_stray_signataire_interim_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationtemplateconfig',
            name='mode_test',
            field=models.BooleanField(default=True),
        ),
    ]
