# Generated by Django 5.2.17 on 2026-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestations', '0008_attestationtemplateconfig_mode_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeattestation',
            name='importance',
            field=models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], default='moyenne', max_length=10),
        ),
    ]
