# Generated by Django 4.2.13 on 2026-05-26 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import employees.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(db_index=True, max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('poste', models.CharField(blank=True, max_length=150, verbose_name='Poste')),
                ('departement', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Département')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('archive', 'Archivé')], default='actif', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'employees',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('CONTRAT', 'Contrat de Travail'), ('RESIDENCE', 'Justificatif de Résidence'), ('FICHE_IEP', 'Fiche IEP'), ('DOSSIER_MED', 'Dossier Médical'), ('DIPLOME', 'Diplôme(s)'), ('PHOTO', "Photo d'identité"), ('AUTRE', 'Document divers')], max_length=30, verbose_name='Type de document')),
                ('file', models.FileField(upload_to=employees.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'tiff'])], verbose_name='Fichier')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Nom original')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('mime_type', models.CharField(blank=True, max_length=50, verbose_name='Type MIME')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Document courant')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='Employé')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document employé',
                'verbose_name_plural': 'Documents employés',
                'db_table': 'employee_documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['employee', 'type_document'], name='idx_doc_emp_type'), models.Index(fields=['employee', 'is_active'], name='idx_doc_active')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['nom', 'prenom'], name='idx_emp_nom_prenom'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['matricule'], name='idx_emp_matricule'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['departement'], name='idx_emp_dept'),
        ),
    ]
