# Generated by Django 4.2.13 on 2026-05-27 13:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_categorie_departement_direction_poste_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('obligatoire', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de document',
                'db_table': 'types_documents',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='type_document',
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='type_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='employees.typedocument', verbose_name='Type de document'),
        ),
    ]
