# Generated by Django 4.2.13 on 2026-06-02 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import employees.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_typedocument_remove_employeedocument_type_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='employeedocument',
            name='mime_type',
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='type_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='employees.typedocument', verbose_name='Type de document'),
        ),
        migrations.CreateModel(
            name='EmployeeDocumentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=employees.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'tiff'])])),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='employees.employeedocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Fichier document',
                'db_table': 'employee_document_files',
                'ordering': ['ordre', 'uploaded_at'],
            },
        ),
    ]
