# Generated by Django 4.2.13 on 2026-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_contrat_employeedocument_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé'), ('demobilise', 'Démobilisé')], default='actif', max_length=20),
        ),
    ]
