# Generated by Django 4.2.30 on 2026-07-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_contrat_statut_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=5, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nin',
            field=models.CharField(blank=True, max_length=30, verbose_name='NIN'),
        ),
        migrations.AddField(
            model_name='employee',
            name='numero_secu_sociale',
            field=models.CharField(blank=True, max_length=30, verbose_name='N° Sécurité Sociale'),
        ),
        migrations.AddField(
            model_name='employee',
            name='rib',
            field=models.CharField(blank=True, max_length=50, verbose_name='RIP/RIB'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name='Date de recrutement'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.poste', verbose_name='Fonction'),
        ),
    ]
