# Generated by Django 4.2.30 on 2026-07-22 17:53

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_groupe_sanguin_employee_nin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.employee_photo_upload_path, verbose_name='Photo'),
        ),
    ]
