# Generated by Django 4.2.30 on 2026-07-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_types', to='employees.typedocument', verbose_name='Catégorie parente'),
        ),
    ]
