# Generated by Django 4.2.30 on 2026-07-25 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_typedocument_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampPersonnalise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('type_champ', models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('date', 'Date')], default='texte', max_length=10, verbose_name='Type')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Champ personnalisé',
                'db_table': 'champs_personnalises',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'ordering': ['type_doc__ordre', 'type_doc__nom'], 'verbose_name': 'Document employé'},
        ),
        migrations.CreateModel(
            name='EmployeeChampValeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='employees.champpersonnalise')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs_personnalisees', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Valeur de champ personnalisé',
                'db_table': 'employee_champs_valeurs',
                'unique_together': {('employee', 'champ')},
            },
        ),
    ]
