# Generated by Django 4.2.30 on 2026-07-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_champpersonnalise_alter_employeedocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFieldLabel',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Libellé de champ système',
                'db_table': 'system_field_labels',
            },
        ),
    ]
