# Generated by Django 4.2.30 on 2026-08-24 18:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_systemfieldlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poles', to='employees.direction', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Pôle',
                'db_table': 'poles',
                'ordering': ['direction__nom', 'nom'],
                'unique_together': {('direction', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cellules', to='employees.departement', verbose_name='Département')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cellules', to='employees.direction', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Cellule',
                'db_table': 'cellules',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements', to='employees.pole', verbose_name='Pôle'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cellule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.cellule'),
        ),
    ]
