# Generated by Django 4.2.30 on 2026-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_pole_cellule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('archive', 'Archivé'), ('demobilise', 'Démobilisé')], default='actif', max_length=20),
        ),
    ]
