# Generated by Django 4.2.30 on 2026-08-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_employee_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_fin_contrat',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat'),
        ),
    ]
