# Generated by Django 4.2.30 on 2026-08-30 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0014_employee_date_fin_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='employees.employee')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.typedocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès employé spécifique',
                'verbose_name_plural': 'Accès employés spécifiques',
                'unique_together': {('user', 'employee', 'type_doc')},
            },
        ),
    ]
