# Generated by Django 4.2.30 on 2026-08-30 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_champ_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='employees.departement', verbose_name='Département')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='employees.direction', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Section',
                'db_table': 'sections',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.section'),
        ),
    ]
