# Generated by Django 4.2.30 on 2026-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_section_employee_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champpersonnalise',
            name='type_champ',
            field=models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('date', 'Date'), ('booleen', 'Booléen (Oui/Non)')], default='texte', max_length=10, verbose_name='Type'),
        ),
    ]
