# Generated by Django 4.2.30 on 2026-08-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_champpersonnalise_type_champ'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='couleur',
            field=models.CharField(blank=True, help_text='Code hexadécimal (ex. #166534), optionnel', max_length=7, verbose_name='Couleur'),
        ),
    ]
