# Generated by Django 4.2.30 on 2026-08-31 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_backfill_typedocument_couleur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Échelle')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Échelle',
                'db_table': 'echelles',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='couleur',
            field=models.CharField(blank=True, help_text='Code hexadécimal (ex. #166534) — assignée automatiquement à la création si non renseignée', max_length=7, verbose_name='Couleur'),
        ),
    ]
