# Generated by Django 4.2.30 on 2026-08-31 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0021_echelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueFonction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_periodes', to='employees.employee')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='employees.poste')),
            ],
            options={
                'verbose_name': 'Historique — Fonction',
                'db_table': 'historique_fonctions',
                'ordering': ['-date_debut'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEchelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('echelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='employees.echelle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_periodes', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Historique — Échelle',
                'db_table': 'historique_echelles',
                'ordering': ['-date_debut'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCategorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='employees.categorie')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_periodes', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Historique — Catégorie',
                'db_table': 'historique_categories',
                'ordering': ['-date_debut'],
                'abstract': False,
            },
        ),
    ]
