# Generated by Django 4.2.30 on 2026-08-31 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_historique_carriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='Chef de cellule'),
        ),
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='Chef de département'),
        ),
        migrations.AddField(
            model_name='direction',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='Directeur'),
        ),
        migrations.AddField(
            model_name='pole',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='Directeur'),
        ),
        migrations.AddField(
            model_name='section',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='Chef de section'),
        ),
        migrations.AddField(
            model_name='service',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee', verbose_name='Chef de service'),
        ),
    ]
