# Generated by Django 4.2.30 on 2026-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_responsable_referentiels'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='champ_source',
            field=models.CharField(blank=True, help_text="Code du champ (système ou personnalisé) que ce document justifie — ex. 'date_naissance', 'nin'. Permet de cliquer sur ce champ dans la fiche employé pour ouvrir directement ce document.", max_length=100, verbose_name='Champ source'),
        ),
    ]
