# Generated by Django 4.2.30 on 2026-08-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_typedocument_champ_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfieldlabel',
            name='ordre',
            field=models.IntegerField(blank=True, default=None, help_text="Position dans l'onglet Paramètres/Champs personnalisés, mélangée avec ChampPersonnalise.ordre. Null = ordre par défaut (position dans SYSTEM_FIELDS côté frontend).", null=True, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='systemfieldlabel',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
