# Generated by Django 4.2.30 on 2026-09-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_systemfieldlabel_ordre_alter_systemfieldlabel_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='champpersonnalise',
            name='categorie',
            field=models.CharField(choices=[('PERSONNEL', 'Personnel'), ('ADMINISTRATIF', 'Administratif')], default='ADMINISTRATIF', help_text="Colonne d'affichage sur la fiche employé (panneau Informations).", max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='champpersonnalise',
            name='is_systeme',
            field=models.BooleanField(default=False, help_text="True pour les 12 champs structurels de la fiche employé (Matricule, Direction, Fonction...) — lignes seedées une fois par migration, jamais créables/supprimables via l'UI. Sert de registre de métadonnées (catégorie + permission), jamais de stockage de valeur : aucune EmployeeChampValeur n'est créée pour un champ is_systeme=True.", verbose_name='Champ système'),
        ),
    ]
