# Generated by Django 4.2.30 on 2026-09-01 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0027_seed_champs_systeme'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeaccessgrant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeaccessgrant',
            name='champ_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.champpersonnalise'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeaccessgrant',
            unique_together={('user', 'employee', 'type_doc', 'champ_personnel')},
        ),
    ]
