# Generated by Django 4.2.30 on 2026-09-02 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_alter_employeeaccessgrant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifArchivage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name="Motif d'archivage")),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Motif d'archivage",
                'db_table': 'motifs_archivage',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='motif_archivage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.motifarchivage', verbose_name="Motif d'archivage"),
        ),
    ]
