# Generated by Django 4.2.30 on 2026-09-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_motifarchivage_employee_motif_archivage'),
    ]

    operations = [
        migrations.AddField(
            model_name='champpersonnalise',
            name='ocr_pattern',
            field=models.CharField(blank=True, choices=[('NIN', 'NIN algérien (18 chiffres)'), ('DATE', 'Date (JJ/MM/AAAA)'), ('TELEPHONE', 'Téléphone algérien'), ('RIB', 'RIB (20 chiffres)'), ('NUM_SECU', 'N° Sécurité Sociale (15 chiffres)'), ('GROUPE_SANGUIN', 'Groupe sanguin'), ('LIEU_NAISSANCE', 'Lieu de naissance (wilaya)')], help_text="Optionnel — active les suggestions OCR pour ce champ dès qu'un document dont le champ_source pointe vers ce champ est uploadé/scanné. Vide = pas d'extraction automatique.", max_length=20, verbose_name='Motif OCR'),
        ),
    ]
