# Generated by Django 4.2.30 on 2026-09-13 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0031_seed_ocr_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocumentfile',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocumentfile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocumentfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
