# Generated by Django 4.2.30 on 2026-09-14 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_employee_updated_by_employeedocumentfile_modified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocumentFilePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la page')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='employees.employeedocumentfile', verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'Page de document',
                'db_table': 'employee_document_file_pages',
                'ordering': ['ordre'],
            },
        ),
    ]
