# Generated by Django 4.2.30 on 2026-09-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_employeedocumentfilepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocumentfile',
            name='rotation',
            field=models.PositiveSmallIntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0),
        ),
        migrations.AddField(
            model_name='employeedocumentfilepage',
            name='rotation',
            field=models.PositiveSmallIntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0),
        ),
    ]
