# Generated by Django 4.2.30 on 2026-09-17 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_employeedocumentfile_rotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecontrat',
            name='duree_indeterminee',
            field=models.BooleanField(default=False, help_text='Si coché, aucun contrat de ce type ne peut avoir de date de fin.', verbose_name='Durée indéterminée'),
        ),
        migrations.AlterField(
            model_name='champpersonnalise',
            name='type_champ',
            field=models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('date', 'Date'), ('booleen', 'Booléen (Oui/Non)'), ('liste', 'Liste (choix unique)')], default='texte', max_length=10, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ChampPersonnaliseOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.CharField(max_length=200, verbose_name='Valeur')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='employees.champpersonnalise')),
            ],
            options={
                'verbose_name': 'Option de champ personnalisé',
                'db_table': 'champs_personnalises_options',
                'ordering': ['ordre', 'valeur'],
            },
        ),
    ]
