# Generated by Django 5.2.17 on 2026-09-17 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_type_contrat_duree_indeterminee_champ_liste'),
    ]

    operations = [
        migrations.AddField(
            model_name='champpersonnalise',
            name='condition_champ',
            field=models.ForeignKey(blank=True, help_text="Optionnel — ce champ n'est affiché (fiche, formulaire, liste) que si l'employé a la valeur `condition_valeur` sur ce champ-là (ex. 'Salaire unique' visible seulement si 'Situation familiale' = 'Marié'). Vide = toujours affiché.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champs_dependants', to='employees.champpersonnalise', verbose_name='Champ conditionnel'),
        ),
        migrations.AddField(
            model_name='champpersonnalise',
            name='condition_valeur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Valeur requise'),
        ),
    ]
