# Generated by Django 5.2.17 on 2026-09-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_champ_personnalise_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motifarchivage',
            options={'ordering': ['nom'], 'verbose_name': 'Motif'},
        ),
        migrations.AddField(
            model_name='motifarchivage',
            name='categorie',
            field=models.CharField(choices=[('archivage', 'Archivage'), ('attestation', 'Attestation de travail')], default='archivage', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='motifarchivage',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Motif'),
        ),
        migrations.AlterUniqueTogether(
            name='motifarchivage',
            unique_together={('nom', 'categorie')},
        ),
    ]
