# Generated by Django 5.2.17 on 2026-09-27 10:07 (édité manuellement : ajout
# du slug en 2 temps — colonne non contrainte, backfill, puis contraintes
# d'unicité — pour ne pas casser sur les lignes déjà en base).

from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(existing_slugs, nom):
    base = slugify(nom)[:150] or 'item'
    slug = base
    n = 2
    while slug in existing_slugs:
        suffix = f'-{n}'
        slug = f'{base[:160 - len(suffix)]}{suffix}'
        n += 1
    existing_slugs.add(slug)
    return slug


def backfill_slugs(apps, schema_editor):
    Direction = apps.get_model('employees', 'Direction')
    Pole = apps.get_model('employees', 'Pole')
    Departement = apps.get_model('employees', 'Departement')
    Service = apps.get_model('employees', 'Service')
    Cellule = apps.get_model('employees', 'Cellule')
    Section = apps.get_model('employees', 'Section')

    seen = set()
    for d in Direction.objects.order_by('nom'):
        d.slug = _unique_slug(seen, d.nom)
        d.save(update_fields=['slug'])

    scopes = {}
    for p in Pole.objects.order_by('direction__nom', 'nom'):
        key = ('pole', p.direction_id)
        p.slug = _unique_slug(scopes.setdefault(key, set()), p.nom)
        p.save(update_fields=['slug'])

    for dep in Departement.objects.order_by('direction__nom', 'nom'):
        key = ('dep', dep.direction_id)
        dep.slug = _unique_slug(scopes.setdefault(key, set()), dep.nom)
        dep.save(update_fields=['slug'])

    for s in Service.objects.order_by('departement__nom', 'nom'):
        key = ('svc', s.departement_id)
        s.slug = _unique_slug(scopes.setdefault(key, set()), s.nom)
        s.save(update_fields=['slug'])

    for c in Cellule.objects.order_by('nom'):
        key = ('cel', c.direction_id, c.departement_id)
        c.slug = _unique_slug(scopes.setdefault(key, set()), c.nom)
        c.save(update_fields=['slug'])

    for sec in Section.objects.order_by('nom'):
        key = ('sec', sec.direction_id, sec.departement_id)
        sec.slug = _unique_slug(scopes.setdefault(key, set()), sec.nom)
        sec.save(update_fields=['slug'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_motif_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='departement',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='direction',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='pole',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160),
        ),
        migrations.RunPython(backfill_slugs, noop_reverse),
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cellule',
            unique_together={('direction', 'departement', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('direction', 'nom'), ('direction', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='pole',
            unique_together={('direction', 'nom'), ('direction', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('direction', 'departement', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('departement', 'nom'), ('departement', 'slug')},
        ),
    ]
