# Generated by Django 5.2.17 on 2026-10-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0038_alter_departement_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champpersonnalise',
            name='ocr_pattern',
        ),
    ]
