# Generated by Django 4.2.13 on 2026-05-26 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, help_text='Conservé même si le compte est supprimé', max_length=50, verbose_name="Login au moment de l'action")),
                ('action', models.CharField(choices=[('VIEW', 'Consultation document'), ('UPLOAD', 'Upload document'), ('DELETE_DOC', 'Suppression document'), ('MODIFY_DOC', 'Modification métadonnées document'), ('CREATE_EMP', 'Création employé'), ('MODIFY_EMP', 'Modification employé'), ('DELETE_EMP', 'Suppression employé'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('LOGIN_FAIL', 'Tentative de connexion échouée'), ('EXPORT', 'Export / Rapport')], max_length=20, verbose_name='Action')),
                ('target_model', models.CharField(blank=True, max_length=50, verbose_name='Modèle cible')),
                ('target_id', models.CharField(blank=True, max_length=36, verbose_name='ID cible')),
                ('target_label', models.CharField(blank=True, help_text="Ex: 'EMP-001 — Jean Dupont'", max_length=255, verbose_name='Libellé cible')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails JSON')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='idx_audit_user_ts'), models.Index(fields=['action', 'timestamp'], name='idx_audit_action_ts'), models.Index(fields=['target_model', 'target_id'], name='idx_audit_target')],
            },
        ),
    ]
