# Generated by Django 4.2.13 on 2026-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VIEW', 'Consultation document'), ('UPLOAD', 'Upload document'), ('DELETE_DOC', 'Suppression document'), ('MODIFY_DOC', 'Modification métadonnées document'), ('CREATE_EMP', 'Création employé'), ('MODIFY_EMP', 'Modification employé'), ('DELETE_EMP', 'Suppression employé'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('LOGIN_FAIL', 'Tentative de connexion échouée'), ('EXPORT', 'Export / Rapport'), ('CREATE_USER', 'Création utilisateur'), ('MODIFY_USER', 'Modification utilisateur (rôle/statut)')], max_length=20, verbose_name='Action'),
        ),
    ]
