# Generated by Django 4.2.30 on 2026-09-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0029_motifarchivage_employee_motif_archivage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('done', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=10)),
                ('raw_text', models.TextField(blank=True, verbose_name='Texte extrait')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Confiance')),
                ('extracted_fields', models.JSONField(blank=True, default=list, help_text='Liste de {champ_code, valeur, confiance, statut} — statut ∈ en_attente/appliquee/ignoree', verbose_name='Champs détectés')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='employees.employeedocumentfile', verbose_name='Fichier')),
            ],
            options={
                'verbose_name': 'Résultat OCR',
                'db_table': 'ocr_results',
            },
        ),
    ]
