# Generated by Django 4.2.30 on 2026-09-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='page_texts',
            field=models.JSONField(blank=True, default=list, help_text="Liste ordonnée du texte de chaque page physique du PDF (index 0 = EmployeeDocumentFilePage.ordre 1) — permet à la recherche globale de retrouver la page exacte d'un résultat, pas seulement le fichier. Vide pour un fichier non-PDF (une image est une page indivisible).", verbose_name='Texte extrait par page'),
        ),
    ]
