# Generated by Django 5.2.17 on 2026-10-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_ocrresult_page_texts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrresult',
            name='extracted_fields',
        ),
    ]
